export type Item={slug:string;title:string;summary:string;applications?:string[];features?:string[]};
export const products:Item[]=[
{slug:'process-equipment',title:'Process Equipment',summary:'Purpose-built equipment for process-intensive industrial applications.',features:['Requirement-led configuration','Custom fabrication options','Inspection-ready documentation'],applications:['Chemical processing','Pharmaceutical operations','Food processing']},
{slug:'reactors',title:'Reactors',summary:'Engineered reactor solutions shaped around your process requirements.',features:['Configurable geometry','Material selection support','Integrated accessory planning'],applications:['Chemical','API & bulk drugs','Biotechnology']},
{slug:'pressure-vessels',title:'Pressure Vessels',summary:'Fabricated vessel solutions for controlled industrial processes.',features:['Design coordination','Fabrication drawings','Quality inspection planning'],applications:['Chemical','Oil & gas','Industrial manufacturing']},
{slug:'storage-tanks',title:'Storage Tanks',summary:'Practical storage systems for liquids, process media and plant operations.',features:['Layout-aware design','Custom connections','Fabricated assemblies'],applications:['Food & beverage','Paint & polymer','Distillery']},
{slug:'heat-exchangers',title:'Heat Exchangers',summary:'Equipment solutions designed for heat transfer duties and plant integration.',features:['Process-led selection','Serviceable layouts','Integration planning'],applications:['Chemical','Pharmaceutical','Petrochemical']},
{slug:'mixers-agitators',title:'Mixers & Agitators',summary:'Mixing equipment concepts for a broad range of processing requirements.',features:['Duty-focused configuration','Drive integration','Vessel coordination'],applications:['Food & beverage','Paint & polymer','Biotechnology']},
{slug:'custom-fabricated-equipment',title:'Custom Fabricated Equipment',summary:'Engineered fabrication for applications that do not fit standard equipment.',features:['Drawing-based manufacture','Practical detailing','Project coordination'],applications:['Industrial manufacturing','Material handling','Process plants']},
{slug:'skid-mounted-systems',title:'Skid-Mounted Systems',summary:'Integrated, modular equipment assemblies prepared for efficient site execution.',features:['Integrated layouts','Piping coordination','Commissioning-ready planning'],applications:['Pharmaceutical','Chemical','Oil & gas']}];
export const services:Item[]=[
{slug:'engineering-design',title:'Engineering & Design',summary:'Convert process requirements into practical, manufacturable engineering solutions.',features:['Equipment design','GA & fabrication drawings','3D modelling and layouts']},
{slug:'process-equipment-manufacturing',title:'Equipment Manufacturing',summary:'Translate approved engineering into dependable fabricated equipment.',features:['Manufacturing planning','Fabrication coordination','Inspection support']},
{slug:'mechanical-fabrication',title:'Mechanical Fabrication',summary:'Fabrication execution aligned to equipment function, fit-up and plant needs.',features:['Laser / CNC fabrication','Custom assemblies','Piping interfaces']},
{slug:'turnkey-epc-solutions',title:'Turnkey EPC Solutions',summary:'Coordinate engineering, manufacturing and site execution through one partner.',features:['Project coordination','Installation planning','Commissioning support']}];
export const industries=['Chemical','Pharmaceutical','API & Bulk Drugs','Food & Beverage','Oil & Gas','Petrochemical','Biotechnology','Distillery & Brewery','Textile','Paper & Pulp','Paint & Polymer','Industrial Manufacturing'];
export const faqs=[['What industries does Aadya Industries serve?','Our solutions are structured for process and manufacturing environments including chemical, pharmaceutical, food and beverage, oil and gas, biotechnology and industrial manufacturing.'],['Do you provide customized equipment?','Aadya Industries is positioned to understand project requirements and develop equipment solutions around them. Share your requirement for a technical discussion.'],['Can you manufacture equipment based on drawings?','Yes. Provide available drawings and requirement details so the team can review scope, manufacturability and execution needs.'],['Do you handle complete turnkey projects?','Turnkey solution support can be discussed based on the engineering, manufacturing, installation and commissioning scope required.'],['How can I request a quotation?','Send your requirement through the enquiry form with available process details, drawings, quantities and timeline expectations.']];
